name: Run setup-hc-releases
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup hc-releases
        uses: hashicorp/setup-hc-releases@v2
        with:
          github-token: ${{ secrets.X_GITHUB_TOKEN }}
      - name: Check version
        run: hc-releases version
      